/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package person.franksuarez.MapPOS.ui;

import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author franksuarez
 */
public class NCRDynakey extends java.awt.Frame {
    private DefaultListModel<String> transactionListModel = new DefaultListModel<>();
    
    
    /**
     * Creates new form NCRDynakey
     */
    public NCRDynakey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtUserInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pnlMid = new javax.swing.JPanel();
        btnDyn1 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        dynLabel1 = new javax.swing.JLabel();
        dynLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlArrowButtons = new javax.swing.JPanel();
        btnUp = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        pnlButtons = new javax.swing.JPanel();
        pnlMainButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        pnlNumbers = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("POS");

        txtUserInput.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setRowHeaderView(null);

        jList1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jList1.setModel(this.transactionListModel);
        jList1.setVisibleRowCount(10);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addComponent(txtUserInput)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMid.setLayout(new java.awt.GridBagLayout());

        btnDyn1.setMaximumSize(new java.awt.Dimension(100, 67));
        btnDyn1.setMinimumSize(new java.awt.Dimension(100, 67));
        btnDyn1.setPreferredSize(new java.awt.Dimension(100, 67));
        btnDyn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDyn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pnlMid.add(btnDyn1, gridBagConstraints);

        jButton25.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton25.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton25.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlMid.add(jButton25, gridBagConstraints);

        jButton26.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton26.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton26.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlMid.add(jButton26, gridBagConstraints);

        jButton27.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton27.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton27.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlMid.add(jButton27, gridBagConstraints);

        jButton28.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton28.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton28.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        pnlMid.add(jButton28, gridBagConstraints);

        jButton29.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton29.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton29.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        pnlMid.add(jButton29, gridBagConstraints);

        jButton30.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton30.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton30.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        pnlMid.add(jButton30, gridBagConstraints);

        jButton31.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton31.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton31.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        pnlMid.add(jButton31, gridBagConstraints);

        dynLabel1.setText("Sign Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlMid.add(dynLabel1, gridBagConstraints);

        dynLabel2.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlMid.add(dynLabel2, gridBagConstraints);

        jLabel3.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlMid.add(jLabel3, gridBagConstraints);

        jLabel4.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlMid.add(jLabel4, gridBagConstraints);

        jLabel5.setText("[Blank]");
        jLabel5.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnlMid.add(jLabel5, gridBagConstraints);

        jLabel6.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        pnlMid.add(jLabel6, gridBagConstraints);

        jLabel7.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        pnlMid.add(jLabel7, gridBagConstraints);

        jLabel8.setText("[Blank]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        pnlMid.add(jLabel8, gridBagConstraints);

        pnlRight.setLayout(new java.awt.GridBagLayout());

        pnlArrowButtons.setMinimumSize(new java.awt.Dimension(200, 200));
        pnlArrowButtons.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlArrowButtons.setLayout(new java.awt.GridBagLayout());

        btnUp.setText("^");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        pnlArrowButtons.add(btnUp, gridBagConstraints);

        btnLeft.setText("<");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        pnlArrowButtons.add(btnLeft, gridBagConstraints);

        btnRight.setText(">");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        pnlArrowButtons.add(btnRight, gridBagConstraints);

        btnDown.setText("V");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        pnlArrowButtons.add(btnDown, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlRight.add(pnlArrowButtons, gridBagConstraints);

        pnlButtons.setLayout(new java.awt.GridBagLayout());

        pnlMainButtons.setLayout(new java.awt.GridBagLayout());

        jButton1.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlMainButtons.add(jButton1, gridBagConstraints);

        jButton2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pnlMainButtons.add(jButton2, gridBagConstraints);

        jButton3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pnlMainButtons.add(jButton3, gridBagConstraints);

        jButton4.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlMainButtons.add(jButton4, gridBagConstraints);

        jButton5.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton5.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlMainButtons.add(jButton5, gridBagConstraints);

        jButton6.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton6.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        pnlMainButtons.add(jButton6, gridBagConstraints);

        jButton7.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton7.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlMainButtons.add(jButton7, gridBagConstraints);

        jButton8.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton8.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton8.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlMainButtons.add(jButton8, gridBagConstraints);

        jButton9.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton9.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton9.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlMainButtons.add(jButton9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlButtons.add(pnlMainButtons, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlRight.add(pnlButtons, gridBagConstraints);

        pnlNumbers.setLayout(new java.awt.GridBagLayout());

        jButton10.setText("7");
        jButton10.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton10.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton10.setPreferredSize(new java.awt.Dimension(67, 67));
        pnlNumbers.add(jButton10, new java.awt.GridBagConstraints());

        jButton12.setText("8");
        jButton12.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton12.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton12.setPreferredSize(new java.awt.Dimension(67, 67));
        pnlNumbers.add(jButton12, new java.awt.GridBagConstraints());

        jButton13.setText("9");
        jButton13.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton13.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton13.setPreferredSize(new java.awt.Dimension(67, 67));
        pnlNumbers.add(jButton13, new java.awt.GridBagConstraints());

        jButton14.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton14.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton14.setPreferredSize(new java.awt.Dimension(100, 67));
        pnlNumbers.add(jButton14, new java.awt.GridBagConstraints());

        jButton11.setText("4");
        jButton11.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton11.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton11.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        pnlNumbers.add(jButton11, gridBagConstraints);

        jButton15.setText("5");
        jButton15.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton15.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton15.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        pnlNumbers.add(jButton15, gridBagConstraints);

        jButton16.setText("6");
        jButton16.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton16.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton16.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        pnlNumbers.add(jButton16, gridBagConstraints);

        jButton17.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton17.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton17.setPreferredSize(new java.awt.Dimension(100, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        pnlNumbers.add(jButton17, gridBagConstraints);

        jButton18.setText("1");
        jButton18.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton18.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton18.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlNumbers.add(jButton18, gridBagConstraints);

        jButton19.setText("2");
        jButton19.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton19.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton19.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlNumbers.add(jButton19, gridBagConstraints);

        jButton20.setText("3");
        jButton20.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton20.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton20.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlNumbers.add(jButton20, gridBagConstraints);

        jButton21.setText("Enter");
        jButton21.setMaximumSize(new java.awt.Dimension(100, 134));
        jButton21.setMinimumSize(new java.awt.Dimension(100, 134));
        jButton21.setPreferredSize(new java.awt.Dimension(100, 134));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        pnlNumbers.add(jButton21, gridBagConstraints);

        jButton22.setText(".");
        jButton22.setMaximumSize(new java.awt.Dimension(67, 67));
        jButton22.setMinimumSize(new java.awt.Dimension(67, 67));
        jButton22.setPreferredSize(new java.awt.Dimension(67, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        pnlNumbers.add(jButton22, gridBagConstraints);

        jButton23.setText("0");
        jButton23.setMaximumSize(new java.awt.Dimension(134, 67));
        jButton23.setMinimumSize(new java.awt.Dimension(134, 67));
        jButton23.setPreferredSize(new java.awt.Dimension(134, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        pnlNumbers.add(jButton23, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlRight.add(pnlNumbers, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        this.transactionListModel.addElement("Up");
        
        
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDyn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDyn1ActionPerformed

        
        
    }//GEN-LAST:event_btnDyn1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.pack();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new NCRDynakey().setVisible(true);
                NCRDynakey d = new NCRDynakey();
                d.setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnDyn1;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel dynLabel1;
    private javax.swing.JLabel dynLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlArrowButtons;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMainButtons;
    private javax.swing.JPanel pnlMid;
    private javax.swing.JPanel pnlNumbers;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTextField txtUserInput;
    // End of variables declaration//GEN-END:variables
}
