/*
 * This source file was generated by the Gradle 'init' task
 */
package person.franksuarez.MapPOS.textclient;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("=========================");
        Client c = new Client();
        
        c.startShell();
    }
}
