/*
 * This source file was generated by the Gradle 'init' task
 */
package person.franksuarez.MapPOS.server;

import person.franksuarez.MapPOS.common.model.Product;
import person.franksuarez.MapPOS.common.model.Transaction;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        
        Transaction t = new Transaction();
        Product p = new Product();
        
        t.addEntry(p);
        
    }
}
